# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20161215_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Currency'),
        ),
    ]
