# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20161215_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
