# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_purchaseorder_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='manager_position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.Area'),
        ),
    ]
