# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20161216_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_iva_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='has_iva',
            field=models.BooleanField(default=False),
        ),
    ]
